### ISSUE TITLE
Question: farrow-pipeline & Building system

### ISSUE THREAD

**Issue by tqma113** [farrow-js/farrow#116]
Is it possible to implement a building system tool library based on farrow-pipeline?

https://mp.weixin.qq.com/s/Zg-snOR7BG6l6DojqzO3Yg

- store: context
- task: combination between pipelines
- build: pipeline.run or other forms

**Comment by Lucifier129** [comment]
I think the answer will be No! 

Since the internal structure behind `farrow-pipeline` is a **list** of middlewares, but the structure behind a `build-system` should be a graph or tree to manage the `dependences graph/tree`, the graph for circular references, the tree for non-circular references.

But `farrow-pipeline` may still be useful for `Task`. Any plain function equipped `farrow-pipeline` can be divided into the combination of some smaller peaces of middlewares, such like the resolver function in `GraphQL`.
